# yaml-language-server: $schema=https://www.schemastore.org/pre-commit-config.json
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: forbid-submodules
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: mixed-line-ending
        args:
          - --fix=lf # Enforce Linux/macOS style (LF)
      - id: end-of-file-fixer
      - id: check-json
      - id: check-symlinks
      - id: detect-private-key
      - id: check-merge-conflict
      - id: sort-simple-yaml
      - id: check-yaml
        args:
          - --unsafe
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials

  - repo: https://github.com/gitleaks/gitleaks
    rev: "v8.30.1"
    hooks:
      - id: gitleaks
        name: Gitleaks
        args:
          - --verbose
          - --redact
          - --no-banner
          - --max-target-megabytes=10
        stages:
          - pre-commit

  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.38.0"
    hooks:
      - id: yamllint
        stages:
          - pre-commit

  - repo: local
    hooks:
      - id: mdformat
        name: Format Markdown
        language: system
        entry: >-
          uvx
          --with "mdformat-gfm"
          --with "mdformat-frontmatter"
          --with "mdformat-shfmt"
          --with "mdformat-config==0.1.3"
          --with "mdformat-ruff"
          --with "mdformat-toc"
          mdformat
        types:
          - markdown

  - repo: local
    hooks:
      - id: agentskills-validate
        name: Validate Skill
        language: script
        entry: ".hooks/validate-skills.py"
        files: >-
          ^skills/
        stages:
          - pre-commit
