# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
tasks:
  pre-commit:
    desc: Run pre-commit hooks
    silent: true
    cmds:
      - |-
        uvx pre-commit run --all-files
